services:
  trilium:
    image: triliumnext/trilium:v0.104.1
    container_name: thg-brain-trilium
    restart: unless-stopped

    environment:
      TZ: Asia/Kolkata
      TRILIUM_NETWORK_TRUSTEDREVERSEPROXY: "10.42.2.0/24"

    ports:
      - "192.168.0.112:8080:8080"

    volumes:
      - /opt/thg-brain-data/trilium-data:/home/node/trilium-data