apiVersion: v1
kind: Service
metadata:
  name: trilium-external
  namespace: thg-apps
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: trilium-external
  namespace: thg-apps
  labels:
    kubernetes.io/service-name: trilium-external
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "192.168.0.112"
    conditions:
      ready: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lore
  namespace: thg-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik

  rules:
    - host: lore.thehighground.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trilium-external
                port:
                  number: 80

  tls:
    - hosts:
        - lore.thehighground.xyz
      secretName: lore-tls
